### ISSUE TITLE
"Limit" & "Sort" Options does not work for backups list

### ISSUE THREAD

**Issue by korkhau** [typhonius/acquia_cli#112]
**Describe the bug**
Acquia API V2 supports offset/limit/sort options. Seems that this tool does not support them.

**To Reproduce**
Steps to reproduce the behavior including calling code:
1. Call **acquiacli database:backup:list {appUuid} {envName} {dbName} --limit 1** for database with few backups
2. See full list of backups returned instead of one

**Expected behavior**
Only one database backup is returned

**Desktop (please complete the following information):**
 - OS: latest macOS & latest Ubuntu
 - 2.0.6

**Comment by typhonius** [comment]
Thanks for this, it looks like there was a `clearQuery` in `db:backup:list` that was wiping the limits, sorts etc. In fixing this, I've also realised that there was a bug in the user agent code so that's being looked at here: https://github.com/typhonius/acquia-php-sdk-v2/issues/87
