### ISSUE TITLE
Allow different config directory definition

### ISSUE THREAD

**Issue by b-sharpe** [typhonius/acquia_cli#15]
When running `acquiaConfigUpdate` it assumes 'sync' as the config directory definition:
`->drush(['config-import', 'sync'])`

Would be great if this could be configurable from the extraconfig or the likes, Acquia for example uses 'vcs' as the default.

**Comment by typhonius** [comment]
That's a good idea, I'm working on some enhancements to this part of the code to make drush steps optional (since some users run these as part of an Acquia Cloud hook) so I'll look to adding in this functionality alongside.

**Comment by typhonius** [comment]
I've added these in https://github.com/typhonius/acquia_cli/commit/0a574915e18c4998de9211c322d11900a54c3a1c. It's probably almost time to tag another release which these changes will be in.
