### ISSUE TITLE
Add in option to automatically respond 'yes' to any question

### ISSUE THREAD

**Issue by typhonius** [typhonius/acquia_cli#16]
We have a number of different commands which use the 'confirm' method allowing the user to respond with a `y` or `n` to double confirm their intent to use the command. Examples of these are:

- Disabling livedev
- Removing domains
- Deleting cron tasks

Advanced users may wish to make these steps completely automated and it would be good to provide an option that responds 'yes' to any confirmation.

**Comment by b-sharpe** [comment]
+1 
We deploy to prod as part of a CI process and can't currently do this with prod:deploy

**Comment by typhonius** [comment]
Hi @b-sharpe, I spent a little bit of time on this today and slotted in a fairly simple fix to address this. Could I ask that you look into the `auto-confirm` branch and the `--yes` option to add to commands typically requiring a confirmation. It looks ok to me but I'd appreciate a second opinion prior to merging to master.

**Comment by b-sharpe** [comment]
@typhonius awesome, thanks. Seems to work, is there (or possibly in future) ever a case where the 'yes' option wouldn't exist? I notice getOption throws an exception if there is no definition for yes

Otherwise, it works and i'm all for it! (would love to get a release with this as well as the optional config steps) :)

**Comment by typhonius** [comment]
@b-sharpe as long as the option is defined (which we do in `src/AcquiaCli.php`) then `getOption` won't throw the exception. Since we're adding in this option, we have control over if we'll ever remove it (which I can't see me doing). On reflection of your comment, we could potentially rename `--yes` to something a bit more specific e.g. `--no-confirm`. Do you have any ideas about a relevant command option?

**Comment by b-sharpe** [comment]
no I think --yes and -y are pretty universal in the drupal/drush world, I would keep as is, also agree if you are defining it as a default option that no need to worry about the exception. Good work!

**Comment by typhonius** [comment]
Thanks - this has been committed, and I've rolled a 1.0.3 version.
