### ISSUE TITLE
Symfony 3 

### ISSUE THREAD

**Issue by AlexSkrypnyk** [typhonius/acquia_cli#3]
Currently, this cannot be installed on the project that uses Symfony 3 components, like filesystem.

I tried to composer require this project but there were simply too many dependency versions to resolve.

@typhonius any chance you could update the project to work with Symfony 3?
I would hate to fork only to update dependencies.

**Comment by typhonius** [comment]
@alexdesignworks is this due to the underlying requirement of the Acquia PHP SDK? There's an issue over here for that: https://github.com/acquia/acquia-sdk-php/issues/78

**Comment by AlexSkrypnyk** [comment]
@typhonius I tried to resolve this by forking acquia/acquia-sdk-php and that solved this specific issue with SDK, but there were problems with other packages, like `acquia/acquia-sdk-php-cloud-api`

**Comment by typhonius** [comment]
@alexdesignworks as far as I can see, `acquia/acquia-sdk-php-cloud-api` is a subtree split of `acquia/acquia-sdk-php`. This project only uses `acquia/acquia-sdk-php-cloud-api` so we may have to fork that project if we can't advocate for the relevant updates/PRs against the existing project.

**Comment by christopher-hopper** [comment]
As the Acquia packages / projects are unmaintained or abandoned I think it's a good opportunity for us to fork their work and start doing the needful to bring it into the current day.

## Let's Go!
![Let's Go!](https://i.ebayimg.com/images/g/F2cAAOSwu4BVm~PB/s-l400.jpg)

**Comment by typhonius** [comment]
I've forked it and will look at the existing PRs in the queue and apply. Help appreciated though :)

**Comment by typhonius** [comment]
Rather than trying to fix the old API SDK, I decided to create a new SDK that would talk to v2 of Acquia Cloud API (https://cloud.acquia.com/api-docs/#).

The SDK is here: https://github.com/typhonius/acquia-php-sdk-v2
The branch of acquia cli that talks to it is acquia-api-v2

It's approaching feature parity but I'll leave this issue open until I'm happy and have used it enough to merge to master.

**Comment by typhonius** [comment]
Closing this with the release of version 1.0.0 of this library that uses the up to date API SDK already linked in this issue.
