### ISSUE TITLE
Code commit task is missing

### ISSUE THREAD

**Issue by sumachaa** [typhonius/acquia_cli#34]
**Describe the bug**
The task list or notification list does not show any activities related to code commit. (CodeDeployed
CodeSwitched)

**To Reproduce**
tried using both v1 & v2
```
./bin/acquiacli task:list $APP
./bin/acquiacli notification:list $APP
```

**Expected behavior**
Should display CodeDeployed, CodeSwitched items in the list

**Additional context**
Not sure whether the Acquia API is not returning these data

**Comment by typhonius** [comment]
I'm seeing similar responses in a couple of my client installs. Can you hit the endpoint directly in a browser to see whether it exists there too: https://cloud.acquia.com/api/applications/{APPLICATION_UUID/notifications

You can find your application UUID with the `application:list` command.

**Comment by sumachaa** [comment]
Thanks @typhonius  for the suggestion.
No, it does not return anything related to Code deploy in there as well. So seems Acquia is not returning these.
