### ISSUE TITLE
Add --latest flag for db:backup:link

### ISSUE THREAD

**Issue by generalredneck** [typhonius/acquia_cli#35]
**Is your feature request related to a problem? Please describe.**
I want to automate grabbing the database without having to write PHP code using acquiacli. Currently I have to do some awesome bashfu to get the first item from `acquiacli db:backup:list` to get the link to the latest backup.

**Describe the solution you'd like**
I would like to have a --latest option that would automaticallly fetch the backup id from the backup list and provide me a link with that or if I don't provide an id it makes the assumption that I meant to grab the latest... much like terminus works for pantheon `terminus backup:get site.live --element=db --to=db.sql.gz`

**Comment by generalredneck** [comment]
So the challenge here too is even if I do something like `acquiacli db:backup:link prod:site prod 123456789` I still end up with a forbidden because it's requiring me to be logged in. Would there be a way to do the same `--to=` flag like terminus does so that you use the session the SDK already established to grab the file and pipe it to a file on the disk?

FYI not trying to come off as complaining. This tool is already essential to my workflow much like terminus and I've only been using it for a day! :)

**Comment by typhonius** [comment]
You’re not coming across as complaining at all; thank you for the contribution. 

If you take a look at the in dev 2.0 branch we’ve included a db download command which allows you to save a db backup to disk. 

I like the idea of latest too.

**Comment by typhonius** [comment]
I've added this into the 2.0 branch of acquia-cli although the release date for that is uncertain. I've changed the default behaviour to be `acquiacli db:backup:download SITENAME ENV DB`.

Users will be able to specify `--path` and `--backup` to customise the download path and backup id, otherwise it will download the latest version to temp.

**Comment by generalredneck** [comment]
@typhonius Sorry about the late test...
I'm getting the following with a fresh composer install on the 2.0 branch while tryign to test this.
```
$ acquiacli db:backup:download prod:sdsuextension prod sdsuextension
➜  Downloading database backup to /tmp/prod-sdsuextension-134653802VZl0qK.sql.gz
    0 [➤⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬]PHP Fatal error:  Uncaught Error: Call to undefined method AcquiaCloudApi\Connector\Client::addOption() in /home/allan/.local/lib/acquia_cli/src/Commands/DbBackupCommand.php:176
Stack trace:
#0 [internal function]: AcquiaCli\Commands\DbBackupCommand->dbBackupDownload('fe919a38-2300-4...', Object(AcquiaCloudApi\Response\EnvironmentResponse), 'sdsuextension', Array)
#1 /home/allan/.local/lib/acquia_cli/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /home/allan/.local/lib/acquia_cli/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /home/allan/.local/lib/acquia_cli/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /home/allan/.local/lib/acquia_cli/vendor/consolidation in /home/allan/.local/lib/acquia_cli/src/Commands/DbBackupCommand.php on line 176
```

**Comment by generalredneck** [comment]
So looks like with this change you will have to bump typhonius/acquia-php-sdk-v2 to ^2.0.4 in composer.lock for the 2.0 branch.
https://github.com/typhonius/acquia_cli/blob/2.0/composer.lock#L2368

You can see the changes where you added `addOption` 25ish days ago here: https://github.com/typhonius/acquia-php-sdk-v2/blob/2.0.4/src/Connector/ClientInterface.php#L83

**Comment by generalredneck** [comment]
Threw in https://github.com/typhonius/acquia_cli/pull/42 to help with this.
