### ISSUE TITLE
Environment Key variables Not working?

### ISSUE THREAD

**Issue by danshumaker** [typhonius/acquia_cli#41]
**Describe the bug**
I'm not able to get the environment variable keys to be used. When the keys are specified within the acquiacli.yml file then acquiacli connects to acquia just fine.  

**To Reproduce**
in bash:
```
vendor/bin/acquiacli application:info XXXXX
export ACQUIACLI_SECRET=ASDFASDFDBASDF
export ACQUIACLI_KEY=ASDFADFASDFASDF
```
On line two of acquiacli.yml file change key value to be bogus value.
On line three of acquiacli.yml file change secret value to be bogus value.

```
vendor/bin/acquiacli application:info XXXXXX
```
The first execution of acquiacli connects and prints info.  The second does not.  Tried several variations of editing the acquiacli.yml to try and ensure that the tool is using the environment variables and not the values in the yml file.  None of the editing variations caused the tool to work.

**Expected behavior**
After either emptying the values of the yml file key and secrets and setting the environment variables appropriately  the tool should connect to acquia.

**Desktop (please complete the following information):**
 - OS:  Mac 10.15.3
[ - Code version/tag : 1.0.3]
- Installed as part of project folder and not as phar standalone.

**Additional context**
Even with a successful connection I get these php warnings:

> PHP Warning:  Declaration of AcquiaCli\Commands\AcquiaCommand::confirm($question) should be compatible with Robo\Tasks::confirm($question, $default = false) in /Users/dan/work/Phase2/webster/webster-bank/vendor/typhonius/acquia_cli/src/Commands/AcquiaCommand.php on line 19

Warning: Declaration of AcquiaCli\Commands\AcquiaCommand::confirm($question) should be compatible with Robo\Tasks::confirm($question, $default = false) in /Users/dan/work/Phase2/webster/webster-bank/vendor/typhonius/acquia_cli/src/Commands/AcquiaCommand.php on line 19

**Comment by typhonius** [comment]
Looks like the tag you're on `1.0.3` doesn't have that enhancement in. Could you verify within your local copy that `src/Commands/AcquiaCommand.php` has the same content as here: https://github.com/typhonius/acquia_cli/blob/master/src/Commands/AcquiaCommand.php#L56-L59

**Comment by danshumaker** [comment]
Thanks Typhonius.  Correct I'm on 1.0.3.  I'll look into using the master branch to solve this issue.. However when specifying that as a dev requirement it looks like I also need the php extension sysvsem - which might imply a php 7.3 version??   We (I) am using docksal for drupal and using a docker image using php 7.2.  I'll see if I can upgrade as our host (Acquia - ha you knew that obviously) is on 7.3.

**Comment by danshumaker** [comment]
So I upgraded docksal to get the default php 7.3 docker image and there are several issues:
composer require --dev typhonius/acquia_cli:dev-master
![acquia_cli](https://user-images.githubusercontent.com/358833/75564513-49153e80-5a1a-11ea-8c2f-0fde14b80429.png)

And then when attempting the installation of php-sysvsem:

![php-sysvsem](https://user-images.githubusercontent.com/358833/75564640-7eba2780-5a1a-11ea-8ac9-b16476d66f61.png)

Any suggestions on what to do?

**Comment by danshumaker** [comment]
Ok, I got this working within docker. ! Yay!

**Comment by typhonius** [comment]
I am going to roll a new release soon so you’ll be able to tag a release and stay off dev-master. 

I’d also encourage you to look at the 2.0 branch as it’s got lots of enhancements that won’t get backported into 1.0.

**Comment by typhonius** [comment]
@danshumaker it might be useful for me to update the documentation for adding sysvsem if that caused issues. Do you have guidance for how you fixed that?

**Comment by danshumaker** [comment]
@typhonius Yes here is Dockerfile.
```
FROM docksal/cli:2.10-php7.3

# LEAVE for setting up acquiacli.yml
#RUN set -xe; \
#	sed -i 's/CHANGE_ME_KEY/test_env_variable/' /home/docker/acquiacli.yml; \

RUN docker-php-ext-configure sysvsem
RUN docker-php-ext-install sysvsem

USER docker

RUN set -e; \
	# Acquia API v2.0
	composer global require typhonius/acquia_cli:dev-master >/dev/null; \
	# Cleanup
	composer clear-cache;

# Switch back to root (IMPORTANT!)
USER root
```

Next on the todo list is make it so environment variables are used instead of acquiacli.yml secret and key and so that authentication is almost automatic.  When I get that working I'll probably submit a PR to docksal.  They are the ones who have all the old acapi v1 baked into their code like this: 

https://github.com/docksal/docksal/blob/develop/bin/fin#L7196
and:
https://github.com/docksal/service-cli/blob/develop/7.3/startup.sh#L117

Looks like you're already on it: https://github.com/docksal/docksal/issues/1062#issuecomment-579511825  :)  

But I'd be glad to help out in anyway I can.

**Comment by danshumaker** [comment]
Ah, and reading through the issues, it seems like my change won't be necessary because they have already handled it here: https://github.com/docksal/service-cli/pull/175/files .

**Comment by danshumaker** [comment]
Hi @typhonius ,  I'm not able to composer require the 2.0 branch.  Any suggestions on the proper syntax?
I've tried:
composer require typhonius/acauia_cli:2.0-dev

**Comment by typhonius** [comment]
The PR for the `2.0.0` branch has now been merged into master and I've tagged a couple of releases. We can either include the Acquia Cli package as-is or as a phar.
