### ISSUE TITLE
Code Switch error

### ISSUE THREAD

**Issue by danshumaker** [typhonius/acquia_cli#43]
**Describe the bug**
"acquiacli c:s uuid branch environment" seems to fail on the second parameter.

**To Reproduce**
Steps to reproduce the behavior including calling code:
1. composer global require typhonius/acquia_cli:2.0.x-dev 
2. authenticate with `acquiacli setup`
3. `acquiacli c:s uuid  tags/asdf  dev`

**Expected behavior**
This command should switch the "dev" server to the tags/asdf branch.

**Screenshots**

![codeSwitch-bug-](https://user-images.githubusercontent.com/358833/75785425-b3d3bc00-5d31-11ea-8abc-1ed5387eaab9.png)

**Desktop (please complete the following information):**
 - OS: Debian Linux 10
 - Code version/tag 2.0

**Additional context**
Error output 
```
Fatal error: Uncaught TypeError: Argument 2 passed to AcquiaCli\Commands\CodeCommand::codeSwitch() must be an instance of AcquiaCloudApi\Response\EnvironmentResponse, string given in /home/docker/.composer/vendor/typhonius/acquia_cli/src/Commands/CodeCommand.php:111
Stack trace:
#0 [internal function]: AcquiaCli\Commands\CodeCommand->codeSwitch('3d2cc3e2-d32d-4...', 'qa-build', Object(AcquiaCloudApi\Response\EnvironmentResponse), Array)
#1 /home/docker/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /home/docker/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /home/docker/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /home/do in /home/docker/.composer/vendor/typhonius/acquia_cli/src/Commands/CodeCommand.php on line 111
```

**Comment by typhonius** [comment]
This is really odd. The correct order should be `uuid environment branch` but I'm seeing the same issue you are. Could you try that order to see if it works and I'll work out why the annotation isn't reflecting that.

**Comment by typhonius** [comment]
It looks like if I remove the type hinting from the function line, it gets rid of the issue and puts things back into the right order.

I'm going to raise a bug over on consolidation/annotated-command as I think this might be coming from there but I can't tell why or how.

**Comment by typhonius** [comment]
Actually, this probably isn't a bug in above libraries, this is probably reflective of how I've used the validate hook to alter a string into an object. I'll take a scan in the codebase for more instances like this and revert.

**Comment by danshumaker** [comment]
@typhonius  I tried switching the parameter order but got an error of not being able to identify either the uuid or the id.  I've confirmed via the old acapi v1.0 that I've got the right uuid and id for the environment in question.

**Comment by typhonius** [comment]
Could you pull the latest 2.0 and test again please? I've pushed a very small update which addresses it on my end.

**Comment by danshumaker** [comment]
Yes thank you @typhonius That fixed it... sort of. It now identifies and launches the task, but is failing to recognize the branch and/or tag.

![naming-issue?](https://user-images.githubusercontent.com/358833/75827506-dbe60e00-5d77-11ea-9910-ec2070ab4a8a.png)

Should I open a different issue?

When looking at Acquia's task log, the initial backups were kicked off as the preparatory step but the code switches were not attempted.

**Comment by typhonius** [comment]
Crap, I know what this is. This is from the inclusion into the SDK of the ability to overwrite Guzzle parameters. Let me fix that and roll a new release now or no POST requests will work.

**Comment by typhonius** [comment]
This should be fixed upstream. If you're able to update your `typhonius/acquia-php-sdk-v2` dependency then this should be resolved.

Once I have added in a more robust solution (as documented in the `@TODO`) then I'll cut a new tag for that library.

**Comment by danshumaker** [comment]
That sounds good ...hmmm updating my sdk-v2 dependency... hmm... umm... Isn't that determined by the composer.json file... that I don't have..? Hmm, I see the acquia_cli/composer.json is the one that requires acquia-php-sdk-v2..  I just did a composer update in that directory (since it looks like you updated the master branch) but that didn't get this change: https://github.com/typhonius/acquia-php-sdk-v2/pull/52/files     I wait for the new tag I guess.  thx for looking into it!

**Comment by typhonius** [comment]
The bounds put in place in the `composer.json` in this package should allow you to update the dependencies underneath too without waiting for a new tag on this package :)

I think the following command should allow you to do this:

`composer update typhonius/acquia-php-sdk-v2 --with-dependencies`.

I did push out a new tag `2.0.6` to address this yesterday too if that would help!

**Comment by danshumaker** [comment]
@typhonius Thanks again. The `composer update typhonius/acquia-php-sdk-v2 --with-dependencies` worked.  I'll also try the updated tag.
