### ISSUE TITLE
--path to allow you to specify filename so we know exactly where the DB is.

### ISSUE THREAD

**Issue by generalredneck** [typhonius/acquia_cli#44]
**Is your feature request related to a problem? Please describe.**
As a user, working on automated deploys, I need the database to be at a specific filename so that my automated script knows where to grab it from.

Example: `acquiacli db:backup:download prod:sdsuextension prod sdsuextenstion --path=./references/latest.sql.gz` makes a file in the folder `./references/latest.sql.gz` with the contents of what ever the backup database file contained.

**Describe the solution you'd like**
It would be wonderful if the `--path` argument would take either a directory or a filename. I'm comparing functionality to terminus. Their command allows a `--to` parameter where you can specify the exact filename. 

**Describe alternatives you've considered**

Other alternatives would be:
* To return the path somehow... I guess I could always grep the output for it?
* To return the file as a stream so that we can pipe it to the place we want... example `acquiacli db:backup:download prod:sdsuextension prod sdsuextenstion > references/latest.sql.gz`
* To get the link to the latest db, but that requires a logged in session to grab it.

For now I'm going to just do a mv using a glob and move it from an always empty directory to the filename I want like `mv /tmp/prod-sdsuextenstion-*.sql.gz` ./references/latest.sql.gz`.

**Additional context**

Here's what happens when I try to do it now

```
$ acquiacli db:backup:download prod:sdsuextension prod sdsuextenstion --path=./db.sql.gz
PHP Notice:  Undefined offset: 0 in /home/allan/.local/lib/acquia_cli/src/Commands/DbBackupCommand.php on line 157
PHP Notice:  Trying to get property 'id' of non-object in /home/allan/.local/lib/acquia_cli/src/Commands/DbBackupCommand.php on line 157
➜  Downloading database backup to ./db.sql.gz/prod-sdsuextenstion-.sql.gz
    0 [➤⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬] [error]  Directory ./db.sql.gz does not exist for sink value of ./db.sql.gz/prod-sdsuextenstion-.sql.gz 
```

**Comment by typhonius** [comment]
Take a look at the latest release of `2.0`. I've included the ability to separately set path and filename in this commit (with sensible defaults if not selected): https://github.com/typhonius/acquia_cli/commit/45f88bd36f53ce0181d94306cc6421c746424fc5

Essentially your command would change to `acquiacli db:backup:download prod:sdsuextension prod sdsuextenstion --path="path/to/directory" --filename="latest"`

**Comment by generalredneck** [comment]
@typhonius It's close... not quite though... the code seems to append .sql.gz to the filename to force it to be that... so `--filename="latest"`is what the command is expecting.

**Comment by typhonius** [comment]
I suppose that's a good question. I've automatically appended .sql.gz to the filename as that will be the format of the file downloaded. I'll leave this for now (with updated instructions to use `--filename='blah'` and then if you think there is a need to change to allow different filenames, that can be put in.

Changing the filename would allow people to save DB backups as jpgs, pngs etc so that's the risk.

**Comment by typhonius** [comment]
@generalredneck do you have any further views on this? I'd like to close this issue out which will let me move on to a manual review/test of all commands before releasing 2.0.0 as stable.

**Comment by generalredneck** [comment]
Oh didn't know you were holding on me :P no this is acceptable, but I was just noting that your command syntax wasn't exactly what you said it was. It's not a biggy as long as we understand how it works! THanks
