### ISSUE TITLE
files:copy exits with error "missing source"

### ISSUE THREAD

**Issue by generalredneck** [typhonius/acquia_cli#45]
**Describe the bug**
![image](https://user-images.githubusercontent.com/526491/76109935-1e3f6300-5fa3-11ea-8fca-9e817132f7c1.png)

**To Reproduce**
Steps to reproduce the behavior including calling code:
1. Checkout latest 2.0 release. (currently 7865e08d3230fdecc26628f9fc23355bd6a635e2)
2. run the command `./bin/acquiacli files:copy REALM:SITENAME prod dev`
3. See error

**Expected behavior**
Other commands are working... just seems to be this one is wonky. Expected to not get an error as this worked with 1.* releases

**Desktop (please complete the following information):**
 - OS: Linux (on acquia itself too)
 - latest 2.0 branch (7865e08d3230fdecc26628f9fc23355bd6a635e2)

**Comment by generalredneck** [comment]
Interesting... so I just had a successful Moving of the DB and had a similar error.
![image](https://user-images.githubusercontent.com/526491/76113104-1f738e80-5fa9-11ea-9458-3aaa3668aa1f.png)

**Comment by ccjjmartin** [comment]
@generalredneck Well that is great that they are deprecating their old version while blockers exist to moving to the new one :man_facepalming: just let me know if I am needed here but it looks like this is blocked for now.

**Comment by typhonius** [comment]
Can you check again with the latest version of 2.0 please? I just verified that the `files:copy` command worked on my instance.

I'm restructuring the entire library for 2.0 so things will continue to change as I knock off command after command to get this all tested :)

**Comment by generalredneck** [comment]
Looks like we are good here!
