### ISSUE TITLE
Wrong example of deploy:prepare

### ISSUE THREAD

**Issue by andrebonon** [typhonius/acquia_cli#51]
**Describe the bug**

Wrong execution when calling acquiacli deploy:prepare.
On the example section on Readme file, it says `acquiacli deploy:prepare UUID, environmentFrom, environmentTo`

```
# Copy the files and db from alpha to dev for testing new code
acquiacli deploy:prepare prod:myacquiasite alpha dev

```
but looking deeply on DeployCommand.php it is `public function deployPrepare($uuid, $environmentTo, $environmentFrom = null)`. 

**Expected behavior**

I believe the expected behavior must be:
```
# Copy the files and db to dev from alpha for testing new code.
acquiacli deploy:prepare prod:myacquiasite **dev alpha** 
```

Also, it could be more clear regarding not passing the last argument, which means that it is going to pull the db and files from production.  

**Additional context**
Tested on acquia_cli:2.0.3 tag.

Thanks for this very helpful project.

**Comment by typhonius** [comment]
Thank you for this report. Would it make sense to have a confirm action in there which prompts the user to agree to the deploy task and to explicitly state the ***from*** and the ***to***?

**Comment by typhonius** [comment]
I'm going to split this into two issues. The bug in the documentation as part of this ticket is seen to in #52 

If you would like a confirm action, I'd see that as new functionality so could you please make a feature request?
