### ISSUE TITLE
Do not perform DB backup during the "code:switch" task until explicitly requested

### ISSUE THREAD

**Issue by aroq** [typhonius/acquia_cli#69]
**Is your feature request related to a problem? Please describe.**
Backup is performed during the `code:switch` task which is not suitable for all cases, e.g. performing a deployment to the PREPROD environment with a lot of huge DBs or delivering an urgent hot-fix to the PRODUCTION environment.

**Describe the solution you'd like**
Do not perform DB backup during the `code:switch` task until explicitly requested with an additional option.

**Describe alternatives you've considered**
Create an option to switch off the backup task (to keep the `code:switch` workflow backward-compatible).

**Comment by typhonius** [comment]
Thanks for this, I think the best option here would be to provide an option to `code:switch` and `code:deploy` that allows users to avoid the backup. I won't change the default as it may have negative effects on other users who are anticipating a backup to coincide with code tasks.

**Comment by aroq** [comment]
Thank you, works perfectly!
