### ISSUE TITLE
WaitForNotification timeout (300s exceeded)

### ISSUE THREAD

**Issue by mattionix** [typhonius/acquia_cli#73]
Hi, first of all thank you for this awesome tool.
I've been facing a issue in the code:switch command. The code is deployed but the "Notification in-progress" step keeps stuck without response and ends crashing by timeout. 

**To Reproduce**
1. Just run code:switch command

**Screenshots**
![AcquiaCli_WaitForNotification_TimeOut](https://user-images.githubusercontent.com/3910454/78802554-5962f680-7994-11ea-928c-03531639d997.png)

**Additional context**
Not sure if is my Acquia application or the notification that acquia_cli is waiting is not being sent by Acquia anymore.
I'm using Acquia_cli on Jenkins (and testing the commands in my machine, i.e screenshot), and using --no-wait fix the question (don't stuck my build in extra 300s).

Please let me know if I can help somehow. Thanks.

**Comment by typhonius** [comment]
Does your code switch task take longer than 5 minutes? If so, it might be worthwhile altering the timeout parameter in your acquiacli config to something higher. You can do this either in your `$HOME/.acquiacli/acquiacli.yml` file or by changing the right environment variable.

If code switching doesn't take longer than 5 minutes (if you do it via the interface), then it'll be something else. `--no-wait` stops your app from pinging Acquia's API for task statuses so will assume that all tasks complete successfully.

**Comment by mattionix** [comment]
No, not at all. The code takes less than 1 minute to deploy, when I switch the branch on Acquia's panel, for example....
Well... at least --no-wait is working like a charm.
