### ISSUE TITLE
A way to retrieve a branch of the current environment?

### ISSUE THREAD

**Issue by hanoii** [typhonius/acquia_cli#97]
I see that `environment:info` can help but is there a way for me to just get the deployed tag/branch of a certain environment? I want to use this on a script.

**Comment by hanoii** [comment]
I came up with 

`acquiacli environment:info $UUID dev | sed -En "/Branch/,/^\| (.*) \|\$/ N; N; s/^\| Branch.*\n.*\n\| ([^ ]*).*/\1/p"`

but it's a rather poor solution :)

**Comment by typhonius** [comment]
I think we could very easily add another command to the `code` namespace. It sounds like this would also benefit from #96 with output in a non-tabular format - is that correct?
